[package]
name = "sferrakl"
version = "0.1.0"
edition = "2024"
default-run = "sferrakl"

[dependencies]
itertools = "0.14.0"
serde = { version = "1.0.228", features = ["default", "std", "alloc", "derive", "rc", "serde_derive"] }
serde_json = "1.0.148"
